# Ex3 - Getting and Knowing your Data



### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np


### Step 2. Read the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

In [3]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"
users = pd.read_csv(url, sep="|", index_col=0)

In [23]:
users.reset_index(drop=True)

age gender     occupation zip_code
0     24      M     technician    85711
1     53      F          other    94043
2     23      M         writer    32067
3     24      M     technician    43537
4     33      F          other    15213
..   ...    ...            ...      ...
938   26      F        student    33319
939   32      M  administrator    02215
940   20      M        student    97229
941   48      F      librarian    78209
942   22      M        student    77841

[943 rows x 4 columns]

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [ ]:
|

### Step 4. See the first 25 entries
Solve it by 2 different ways (con metodo y con slicing)

In [24]:
users.head(25)

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [25]:
users.iloc[:25, :]

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

In [27]:
users.iloc[-25:, :]

age gender     occupation zip_code
user_id                                    
919       25      M          other    14216
920       30      F         artist    90008
921       20      F        student    98801
922       29      F  administrator    21114
923       21      M        student    E2E3R
924       29      M          other    11753
925       18      F       salesman    49036
926       49      M  entertainment    01701
927       23      M     programmer    55428
928       21      M        student    55408
929       44      M      scientist    53711
930       28      F      scientist    07310
931       60      M       educator    33556
932       58      M       educator    06437
933       28      M        student    48105
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [26]:
users.tail(25)

age gender     occupation zip_code
user_id                                    
919       25      M          other    14216
920       30      F         artist    90008
921       20      F        student    98801
922       29      F  administrator    21114
923       21      M        student    E2E3R
924       29      M          other    11753
925       18      F       salesman    49036
926       49      M  entertainment    01701
927       23      M     programmer    55428
928       21      M        student    55408
929       44      M      scientist    53711
930       28      F      scientist    07310
931       60      M       educator    33556
932       58      M       educator    06437
933       28      M        student    48105
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

### Step 6. What is the number of observations in the dataset?
Solve it by 2 different ways

In [30]:
users.shape[0]

943

### Step 7. What is the number of columns in the dataset?
Solve it by 2 different ways

In [31]:
users.shape[1]

4

### Step 8. Print the name of all the columns.

In [32]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed? Get the index values

In [33]:
users.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?
Solve it by 2 different ways

In [38]:
type(users.info())

<class 'pandas.core.frame.DataFrame'>
Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   age         943 non-null    int64 
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 36.8+ KB


NoneType

In [42]:
users.dtypes.iloc[0], users.dtypes.loc["age"]

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column
Solve it by 2 different ways

In [51]:
lista = [1,2,3]
lista[0:1]

[1]

In [65]:
users.loc[:, "occupation"].value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

### Step 12. How many different occupations are in this dataset? How many users per occupation are in the dataset?

In [69]:
users.loc[:, "occupation"].nunique()

21

### Step 13. What is the most frequent occupation?

In [70]:
users.loc[:, "occupation"].value_counts().index[0]

'student'

### Step 14. Summarize the DataFrame.

In [72]:
users.describe()

age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### Step 15. Summarize all the columns

In [73]:
users.describe(include="all")

age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [76]:
users.loc[:, ["occupation"]].describe()

occupation
count         943
unique         21
top       student
freq          196

### Step 17. What is the mean age of users?

In [77]:
users.loc[:, ["age"]].mean()

age    34.051962
dtype: float64

### Step 18. What is the age with least occurrence?

In [82]:
users_VC = users.loc[:, "age"].value_counts()
minimo = users_VC.min()


mask = users_VC == minimo

users_VC.loc[mask].index

Index([7, 11, 66, 10, 73], dtype='int64', name='age')

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a[0:1, :]

array([[1, 2, 3]])

In [19]:
a[0, :]

array([1, 2, 3])

In [8]:
minimo = users["age"].value_counts().values.min()
minimo

np.int64(1)

In [9]:
mask = users["age"].value_counts() == min

In [11]:
users["age"].value_counts().loc[mask]

age
7     1
11    1
66    1
10    1
73    1
Name: count, dtype: int64